quarkus.http.port=8124
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000,http://localhost:8124
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.access-control-max-age=3600